# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project\GameProject\Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameWindow = QtWidgets.QFrame(self.centralwidget)
        self.frameWindow.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.frameWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWindow.setObjectName("frameWindow")
        self.frame = QtWidgets.QFrame(self.frameWindow)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 791, 541))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.mainTextBox = QtWidgets.QPlainTextEdit(self.frame)
        self.mainTextBox.setGeometry(QtCore.QRect(130, 20, 501, 281))
        self.mainTextBox.setReadOnly(True)
        self.mainTextBox.setObjectName("mainTextBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionLoad_Game = QtWidgets.QAction(MainWindow)
        self.actionLoad_Game.setObjectName("actionLoad_Game")
        self.actionSave_Game = QtWidgets.QAction(MainWindow)
        self.actionSave_Game.setObjectName("actionSave_Game")
        self.actionExit_Game = QtWidgets.QAction(MainWindow)
        self.actionExit_Game.setObjectName("actionExit_Game")
        self.menuMenu.addAction(self.actionNew_Game)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionLoad_Game)
        self.menuMenu.addAction(self.actionSave_Game)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit_Game)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))
        self.actionLoad_Game.setText(_translate("MainWindow", "Load Game"))
        self.actionSave_Game.setText(_translate("MainWindow", "Save Game"))
        self.actionExit_Game.setText(_translate("MainWindow", "Exit Game"))
